[package]
edition = "2024"
name = "user"
publish = false
version = "0.1.0"

[features]
all = ["interface-demo/all"]

[dependencies]
interface-demo = {path = "../interface"}
trait-ffi = {path = "../.."}
